version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3060:3060"  # Map host port 3070 to container port 3070
    restart: always
    environment:
      NODE_ENV: production  # Set environment variables as needed
