name: Deploy to Server

on:
  push:
    branches:
      - dev 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Store your private key in GitHub Secrets

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no root@162.241.149.204 << 'EOF'
            # Navigate to the project directory
            cd /srv/intranet/backend || exit
            
            # Pull the latest changes from the dev branch
            git pull origin dev
            
            # Install dependencies (if you're using npm)
            npm install
            
            # Restart your application (if you're using PM2, for example)
            pm2 restart all  # or specify your app name, e.g., pm2 restart my-app
            
            # Optionally, run any migrations or build steps
            # npm run build  # Uncomment if needed
          EOF
