name: Deploy to Server

on:
  push:
    branches:
      - dev 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: SHA256:L1qh9hBRloYeraJQ+AHWAd/76TaqEbDtOI0ikrqe74M
      - name: Deploy to server
        run: |
          ssh root@162.241.149.204 "cd /srv/intranet/backend && git pull origin main"
