name: Deploy to Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step to build the frontend
      - name: Build React app
        working-directory: frontend  # Corrected path
        run: |
          npm install
          npm run build

      - name: Deploy to server
        run: |
          # Deploy backend
          ssh -o StrictHostKeyChecking=no root@162.241.149.204 << 'EOF'
            cd /var/www/vhosts/zaptas.in/intranet2.zaptas.in/garware/backend || exit
            git pull origin dev
            npm install
            pm2 restart all
          EOF

      # Step to deploy the frontend build files
      - name: Deploy frontend build to server
        run: |
          rsync -avz --delete frontend/build/ root@162.241.149.204:/var/www/vhosts/zaptas.in/intranet2.zaptas.in/garware/frontend/
          
          # Restart Nginx if necessary
          ssh -o StrictHostKeyChecking=no root@162.241.149.204 << 'EOF'
            systemctl restart nginx
          EOF
