name: Deploy to Server

on:
  push:
    branches:
      - dev 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no root@162.241.149.204 << 'EOF'
            # Navigate to the project directory
            cd /srv/intranet || exit
            
            # Pull the latest changes from the dev branch
            git pull origin dev
            
            # Build the Docker image
            docker-compose build
            
            # Start or restart the Docker container
            docker-compose up -d
            
            # Optionally, run any migrations or build steps
            # npm run build  # Uncomment if needed
          EOF
